CMake Fixes
FLAMEGPU/FLAMEGPU2 pull request #1062
Opened 2023-04-21 09:37 UTC by ptheywood

A number of fixes and additions to FLAMEGPU2's CMake encountered when working on a more complex tempalte model.

+ [x] `flamegpu_new_linter_target` fix. Closes #1057 
+ [x] Make the `lint_flamegpu` target OFF by default when this repo is not he primary CMake. Closes #1045 
+ [x] Make the `docs` target OFF by default when this repo is not primary
+ [x] Add `flamegpu_add_library`, for creating static libraries which are more than just linked against FLAMEGPU2 (i.e. warning levels MSVC + CUDA fixes etc. This allows the creation of unit-testable FLAMEGPU 2 simulators.
+ [x] Some Refactoring, to reduce dupliocation
+ [x] Demonstrate `flamegpu_add_library` in an existing example. This may not actually be desirable for merging.
+ [ ] Fix `source_group` errors (#1051). requires testing / development on Windows.

2023-09-12 17:38 UTC, Robadob commented
I've no strong preference, removing the redundant `src` seems fine.

2023-09-13 09:44 UTC, ptheywood commented
>  removing the redundant src seems fine.

For examples we can't really do that, as the src dir may not exist (which could cause errors / issues with the source grouping before) and would then potentially cause folder conflicts, if say the user had this (unwise) setup

```
├── a
│   └── b.h
└── src
    └── a
        └── b.h
```

Then intentionally removing src would cause both `a`'s to be the same filter, which contain files with the same name which I'm not sure how VS would handle. 

---

We probably could for the flamegpu target, but its probably simpler / more consistent to keep it.

I'll make the change when I'm back in windows at some point. 

---

The CI failure is just from my low-effort testing of the folder structures / CMake, so once I drop the appropraite commit it pass.

2023-09-13 10:32 UTC, Robadob commented
> > removing the redundant src seems fine.
> 
> For examples we can't really do that, as the src dir may not exist (which could cause errors / issues with the source grouping before) and would then potentially cause folder conflicts, if say the user had this (unwise) setup
> 
> ```
> ├── a
> │   └── b.h
> └── src
>     └── a
>         └── b.h
> ```
> 
> Then intentionally removing src would cause both `a`'s to be the same filter, which contain files with the same name which I'm not sure how VS would handle.
> 
> We probably could for the flamegpu target, but its probably simpler / more consistent to keep it.
> 
> I'll make the change when I'm back in windows at some point.
> 
> The CI failure is just from my low-effort testing of the folder structures / CMake, so once I drop the appropraite commit it pass.

As I said, no strong preference do what you think best. It's hard to go wrong.

2023-09-21 16:59 UTC, ptheywood commented
I've now made the source_group change to the FLAMEGPU target, so that it places things into the CMake default filters of `Header Files` and `Source Files`, but using tree within the `FLAMEGPU_ROOT` directory (must use `FLAMEGPU_ROOT` as `include` is above `src/CMakeLists.txt`). 

This makes it nest deeper, but is consistent.

![image](https://github.com/FLAMEGPU/FLAMEGPU2/assets/628937/246ad26e-dcbd-4111-a084-802a9abfbe38)

I'm not strongly opinionated either way, so if you don't like this we can drop the final commit and still merge this anyway.

---

I've also removed the example(s) which showed the previous CMake failures, as they were messy and I'm not aware of a nice way to have a CMake test suite. I have pushed them to another branch [`cmake-fixes-rc1-with-example`](https://github.com/FLAMEGPU/FLAMEGPU2/tree/cmake-fixes-rc1-with-example) if you would like to test them.

Otherwise this PR is ready for review.

2023-09-22 12:27 UTC, Robadob requested changes
> CMake: Demonstrate use of flamegpu_add_library on the host_fucntions example. Maybe don't merge?

Would require example readme discussing, or delete commit

2023-09-22 13:56 UTC, ptheywood commented
I've now dropped the missed "probably don't merge" commit, which was just a test case demonstrating the library use case rather than binary. I'll open an issue to document it on the docs repo and / or use it in a standalone example in the future too.

2023-09-22 14:19 UTC, Robadob approved these changes
LGTM

2023-09-22 15:04 UTC, merged