2.0.0-rc.2 final changes
FLAMEGPU/FLAMEGPU2 pull request #1248
Opened 2024-11-18 20:07 UTC by ptheywood

Final changes required for the 2.0.0-rc.2 release

+ [ ] Merge required PRs
  + [ ] #1245
  + [ ] #1247
+ [x] Update CHANGELOG.md
  + [ ] Double check the date
+ [ ] Update Citation.cff
+ [ ] Push vis repo tag and update hash
+ [ ] Double check produced wheels from #1247 are usable

Closes #1246

Once this is merged, the tag can be pushed and release notes written.

2024-11-19 11:25 UTC, ptheywood commented
Target release date for 2024-11-22, so @mondus can look at #1212

2024-11-19 11:57 UTC, ptheywood commented
I have a local branch ready to push once rebased on the lint + swig/CMake PRs ready to go,excluding the potentialy telemetry change. 

(I don't want to trigger the ~50 CI jobs again until I have to).

2024-11-22 11:27 UTC, Robadob requested changes

2024-11-22 11:27 UTC, Robadob commented on CHANGELOG.md
> ++ Add visualisation support for Environment Directed Graphs ([#1239](https://github.com/FLAMEGPU/FLAMEGPU2/pull/1239))
This feature was also in that PR
https://github.com/FLAMEGPU/FLAMEGPU2/pull/1239/commits/e574f2ede68c6430a3917449cbf4b95e914fe680

```suggestion
+ Add visualisation support for Environment Directed Graphs ([#1239](https://github.com/FLAMEGPU/FLAMEGPU2/pull/1239))
+ Add visualisation support for setting the initial camera roll angle ([#1239](https://github.com/FLAMEGPU/FLAMEGPU2/pull/1239))
```

2024-11-22 11:40 UTC, Robadob approved these changes

2024-11-22 11:42 UTC, merged