Empty commit so I can create draft PR
FLAMEGPU/FLAMEGPU2 pull request #457
Opened 2021-03-02 23:13 UTC by Robadob

WIP PR for `FLAMEGPU_HOST_API` direct access to agent data.

This needs some discussion/thought before implementation as there are various considerations re:performance.

@ptheywood proposed this usage example in #246

```c++
FLAMEGPU_STEP_FUNCTION(step_function) {
    // Get a population
    auto population = FLAMEGPU_HOST->agentPopulation("agent");

    // Perform a parallel reduction over the whole population
    int sum_a = population.sum<int>("a");

    // Iterate the population on teh host
    for(auto agentInstance : population){
        // Access variables - with JIT copying
        float x = agentInstance.getVariable<float>("x");
        // Host modification, sets flags to push to device when required
        agentInstance.setVariable<float>("x", x+1);

        // Possibly support host agent death, by marking the agent to be terminated at the end of the step func? This has many edge cases
        agentInstance->die(); 
    }

    // Also support setting a common value over the entire population.
    population.set<float>("x", 1.0f);

    // Another reduction would invoke a push before, otherwise results would be out of sync.

    // Birth new agents. This has edge cases if parallel reductions occur before function ends
    auto newInstance = population.newAgent();
    newInstance.setVariable<float>("x", 0.0f);

    // Automatically push modified data to the device, if required pushing as few bytes as possible (within reason)
```

However this raises some questions:
* Is `FLAMEGPU_HOST->agentPopulation("agent");` supposed to return an (equivalent to) `AgentVector`
* If `population` is equivalent to `AgentVector`, why is it `AgentInstance::die()`, rather than `AgentVector::erase()
* Should a host api reduction really cause downloaded agent populations to be upload early?
     * If that's the case, should host agent birth also be applied early?
* The downloaded populations are automatically re-uploaded to device.
* Direct access to agents via an `AgentVector` analogue, essentially makes (the more efficient?) host agent birth redundant. Should this be removed?
* Should the host reductions be accessible via the `AgentVector` analogue or should the analogue be distinct, and named in a manner to discourage use?

It seems as though this `HostAgentVector` should wrap a regular agent vector, providing essentially duplicate functionality with additional features for creating an effective changelog, to reduce data transfer. It will also need to link pretty deeply with the HostAPI object, to be checked whenever a reduction occurs.

Simplifying these mechanics, at the cost of performance could be preferable, so this requires discussion.

Relates to #246
Closes #51 
Closes #71

2021-03-03 11:15 UTC, ptheywood commented
> If population is equivalent to AgentVector, why is it AgentInstance::die(), rather than `AgentVector::erase(). I would expect consistency to be preferable.

I'll have just been thinking about  it from a modelling perspective (i.e. agent death) hence `die()`. I agree that consistency is preferable.

> With regards to mechanics of the changelog. Tracking the first and last modified items for each variable is the obvious way to go. Allowing copies to minimised. Obviously certain methods would savage this, and essentially require all agents to be updated.

For (very/quite) small pops (of relatively skinny agents) in F1 it was cheaper to just copy  the entire SoA at once than do many small copies. 
I think in the end I implemented explicit copying of a requested variable at once. 
Given memcpy latency and higher achieved bandwidth for larger copies first-last tracking should be fine IMO. 


> * [ ]  Should the downloaded agent data be automatically updated at the end? (otherwise user must explicitly commit changes).

Either could work, its a trade off between ease of use and performance. Explicit is probably easier for us, but does shift some extra thought onto the modeller.

> * [ ]  Should an agent reduction force upload agent data (and clear the change log)

If automatic h2d then yes, if not then no?
For small vectors it might even be worth adding host based reductions (cheaper to just do it on the host than doing h2d, reduction, d2h) but that's not a priority.

> * [ ]  Should the host-agent reductions be moved inside the `AgentVector` analogue?

If they are only applicable to agents in a single state then yes.
If agnets in multiple states are contiguous and the reductions can be applied across all agents of a given type thne no (I don't think this is currently the case?)

> * [ ]  Should `HostAgentInstance` be renamed `HostAgentTools` (or something else?)

Yes. It doesn't represent an individual agent anyway in the host api.

> * [ ]  Should the changelog be built into `AgentVector` to make dependent class far simpler.

It's probably a bitfield per variable in the class so shouldn't be too much overhead? I'm indifferent on this really. 


> * [ ]  How much `AgentVector` functionality should be exposed? (e.g. do we want to go as far as allowing them to insert externally defined `AgentVector`s?

Not sure if inserts required. Appending a separate agent vector could be useful (i.e. mass birth)

2021-03-08 20:06 UTC, Robadob commented
ffs only linted the lib and forgot to commit the changes to the test suite.

2021-03-08 23:13 UTC, Robadob commented
It's now pyfgpu failing, which I haven't looked into (didn't expect it to break, but quite a few reasons it might).

2021-03-09 10:16 UTC, Robadob commented
I've had a look into the pyflamegpu build failure.

It's related to the private structure `DeviceAgentVector::VariableBufferPair` not having a copy constructor. For some reason SWIG requires it have to have one, but regular compilation doesn't (perhaps SWIGs replacement for `#include <list>`?).

Not immediatley clear how to fix, so will leave broken until I have the rest of the PR implemented.

2021-03-11 15:23 UTC, Robadob commented
Host agent birth seems a bit complicated.

* Host birth only, existing behaviour
* Host birth before DeviceAgentVector (is changed), copy agents from host birth structure to DeviceAgentVector (trigger insert directly after construction?)
* Host birth after DeviceAgentVector (if changed, but before sync), copy agents directly to DeviceAgentVector (essentially trigger insert?).

2021-03-15 13:59 UTC, Robadob commented
> Host agent birth seems a bit complicated.
> 
> * Host birth only, existing behaviour
> * Host birth before DeviceAgentVector (is changed), copy agents from host birth structure to DeviceAgentVector (trigger insert directly after construction?)
> * Host birth after DeviceAgentVector (if changed, but before sync), copy agents directly to DeviceAgentVector (essentially trigger insert?).

I think the simplest way to handle this, will be to make the HostAgentBirth buffer/s update the DeviceAgentBirth buffers when a `_requires()` method is called. I think I can tweak those, so the requires is passed pos, before the index is validated.

2021-03-25 11:40 UTC, Robadob commented
Test which remain:
- [x] `HostAgentAPI` reductions sync changes from `DeviceAgentVector`
- [ ] `HostAgentAPI` sort sync changes from `DeviceAgentVector` before, and `DeviceAgentVector` syncs after (not recommended, but possible).
- [ ] Host agent birth is noticed by all `DeviceAgentVector` methods (and `HostAgentAPI` reductions?).

2021-03-29 16:58 UTC, ptheywood requested changes
Generally looks good, although I've not been too thorough given the number of changes. 

7 tests fail under linux with seatbelts on in release mode:

```
[==========] 764 tests from 55 test suites ran. (345596 ms total)
[  PASSED  ] 757 tests.
[  FAILED  ] 7 tests, listed below:
[  FAILED  ] HostReductionTest.SumException
[  FAILED  ] HostReductionTest.MinException
[  FAILED  ] HostReductionTest.MaxException
[  FAILED  ] HostReductionTest.CustomReductionException
[  FAILED  ] HostReductionTest.HistogramEvenException
[  FAILED  ] HostReductionTest.CustomTransformException
[  FAILED  ] HostReductionTest.CountException
```

```
[ RUN      ] HostReductionTest.SumException
/home/ptheywood/code/flamegpu/FLAMEGPU2/tests/test_cases/runtime/host_reduction/test_misc.cu:15: Failure
Expected: FLAMEGPU->agent("agedddnt") throws an exception of type InvalidCudaAgent.
  Actual: it throws std::out_of_range with description "_Map_base::at".
[  FAILED  ] HostReductionTest.SumException (0 ms)
[ RUN      ] HostReductionTest.MinException
/home/ptheywood/code/flamegpu/FLAMEGPU2/tests/test_cases/runtime/host_reduction/test_misc.cu:22: Failure
Expected: FLAMEGPU->agent("agsssedddnt") throws an exception of type InvalidCudaAgent.
  Actual: it throws std::out_of_range with description "_Map_base::at".
[  FAILED  ] HostReductionTest.MinException (1 ms)
[ RUN      ] HostReductionTest.MaxException
/home/ptheywood/code/flamegpu/FLAMEGPU2/tests/test_cases/runtime/host_reduction/test_misc.cu:29: Failure
Expected: FLAMEGPU->agent("ageaadddnt") throws an exception of type InvalidCudaAgent.
  Actual: it throws std::out_of_range with description "_Map_base::at".
[  FAILED  ] HostReductionTest.MaxException (0 ms)
[ RUN      ] HostReductionTest.CustomReductionException
/home/ptheywood/code/flamegpu/FLAMEGPU2/tests/test_cases/runtime/host_reduction/test_misc.cu:36: Failure
Expected: FLAMEGPU->agent("ageaadddnt") throws an exception of type InvalidCudaAgent.
  Actual: it throws std::out_of_range with description "_Map_base::at".
[  FAILED  ] HostReductionTest.CustomReductionException (1 ms)
[ RUN      ] HostReductionTest.HistogramEvenException
/home/ptheywood/code/flamegpu/FLAMEGPU2/tests/test_cases/runtime/host_reduction/test_misc.cu:43: Failure
Expected: FLAMEGPU->agent("ageaadddnt") throws an exception of type InvalidCudaAgent.
  Actual: it throws std::out_of_range with description "_Map_base::at".
[  FAILED  ] HostReductionTest.HistogramEvenException (1 ms)
[ RUN      ] HostReductionTest.CustomTransformException
/home/ptheywood/code/flamegpu/FLAMEGPU2/tests/test_cases/runtime/host_reduction/test_misc.cu:52: Failure
Expected: FLAMEGPU->agent("ageaadddnt") throws an exception of type InvalidCudaAgent.
  Actual: it throws std::out_of_range with description "_Map_base::at".
[  FAILED  ] HostReductionTest.CustomTransformException (0 ms)
[ RUN      ] HostReductionTest.CountException
/home/ptheywood/code/flamegpu/FLAMEGPU2/tests/test_cases/runtime/host_reduction/test_misc.cu:59: Failure
Expected: FLAMEGPU->agent("ageaadddnt") throws an exception of type InvalidCudaAgent.
  Actual: it throws std::out_of_range with description "_Map_base::at".
[  FAILED  ] HostReductionTest.CountException (1 ms)

```

2021-03-29 19:32 UTC, Robadob commented
Fixed all the tests I forgot to check.

Windows/Debug/Seatbelts
```
[==========] 750 tests from 54 test suites ran. (882411 ms total)
[  PASSED  ] 750 tests.

  YOU HAVE 18 DISABLED TESTS
```

```
================================= 445 passed in 106.37s (0:01:46) =================================
```

2021-03-30 09:20 UTC, ptheywood approved these changes
Tests all pass under linux now

2021-03-31 12:40 UTC, Robadob commented
Todo: query PIMPL in ukrse slack cpp channel (#466).

2021-04-12 15:27 UTC, Robadob commented
C and Python tests pass.

The current version has `HostAgentAPI` return a `DeviceAgentVector` which is just a typedef for `DeviceAgentVector_impl&`.

This has the benefit over my previous iteration, of being more maintainable (all the functions aren't manually wrapped. However, creates the problem of us being unable to detect if a user holds onto the reference after the end of the host function it was created in.

2021-04-14 13:39 UTC, merged