Draft of RTC #Line
FLAMEGPU/FLAMEGPU2 pull request #615
Opened 2021-08-04 10:14 UTC by Robadob

This is currently a draft, we need to decide how we want these line numbers to appear.

e.g.

If a user has not got `EXPORT_RTC_SOURCES` enabled, then their only reference to line, is the string/file they pass to FLAMEGPU. So first line of that should be line 1 (ignoring injected includes etc).

If a user has got `EXPORT_RTC_SOURCES` enabled, then instead it can be assumed they will be referring to the exported files. In which case, the start of that string should be appended `#line 2 filename`. 2, because the exported source will include the `#line` statement on line 1.

I'm not really a fan of this inconsistency, but it makes sense. So if agreed I will tweak the PR to handle those cases.

Addresses #608

2021-08-04 17:24 UTC, ptheywood commented
Sounds like the best choice, although i agree that the inconcistency feels a bit grim, but probably the most useful / practical option.

2021-08-13 08:51 UTC, Robadob commented
Another thought, re RTC agent functions defined in code. They open the string on it's own line. So presumably the string begins with a newline, so really want to trim that opening newline if it exists, because no one is considering an empty newline line 1

2021-08-13 16:15 UTC, ptheywood requested changes
Have you ran the  full test suite on this? I get errors with RTC function conditions

```
[  FAILED  ] 2 tests, listed below:
[  FAILED  ] DeviceRTCAPITest.AgentFunction_cond_rtc
[  FAILED  ] RTCMultiThreadDeviceTest.SameModelMultiDevice_AgentFunctionCondition
```

```
[ RUN      ] DeviceRTCAPITest.AgentFunction_cond_rtc
---------------------------------------------------
--- JIT compile log for #line 1 "rtc_test_func_impl_condition.cu" ---
---------------------------------------------------
#line 1 "rtc_test_func_impl_condition.cu"(1): error: this declaration has no storage class or type specifier

limits(7): error: expected a ";"

limits(50): warning: parsing restarts here after previous syntax error

limits(51): error: expected a declaration

limits(108): error: expected a declaration

limits(111): warning: parsing restarts here after previous syntax error

limits(112): error: numeric_limits is not a template

limits(113): error: name followed by "::" must be a class or namespace name

limits(113): error: expected an identifier

limits(113): error: not a class or struct name

limits(113): error: class or struct definition is missing

At end of source: warning: parsing restarts here after previous syntax error

At end of source: error: expected a ";"

10 errors detected in the compilation of "#line 1 "rtc_test_func_impl_condition.cu"".

---------------------------------------------------
unknown file: Failure
C++ exception with description "/home/ptheywood/code/flamegpu/FLAMEGPU2/src/flamegpu/util/detail/JitifyCache.cu(331): Error compiling runtime agent function (or function condition) ('rtc_test_func_condition'): function had compilation errors (see std::cout), in JitifyCache::buildProgram()." thrown in the test body.
```

2021-08-13 16:22 UTC, Robadob commented
Nope, will get around to that Monday. Good shout, was supposed to be a simple change.

2021-08-13 16:23 UTC, Robadob commented
I presume it's the same issue I had on agent functions, I just forgot to remove the breaking bit from conditions too.

2021-08-13 16:29 UTC, Robadob commented
It can't be, that's one bit of code so same fix applies.

Looking at this, it might not even like the `#line` statement

> `#line 1 "rtc_test_func_impl_condition.cu"(1): error: this declaration has no storage class or type specifier`

2021-08-13 19:33 UTC, Robadob commented
Debug build.
```
[----------] Global test environment tear-down
[==========] 868 tests from 68 test suites ran. (791154 ms total)
[  PASSED  ] 868 tests.

  YOU HAVE 38 DISABLED TESTS
```

2021-08-14 12:24 UTC, ptheywood approved these changes
Linux tests now all pass.

2021-08-14 13:11 UTC, merged