Invalid XML input file test fixes
FLAMEGPU/FLAMEGPU2 pull request #810
Opened 2022-02-23 17:56 UTC by ptheywood

Closes #808

* Uses a `EXPECT_EXIT` in the google test, this emits a warning.
* SKips the python test, as cannot trap the C/C++ call to `exit`.

2022-02-23 17:58 UTC, ptheywood commented
Linux release, seatbelts=OFF tests:

```
[==========] Running 871 tests from 77 test suites.
[----------] Global test environment set-up.
[----------] 1 test from TestSimulationDeathTest
[ RUN      ] TestSimulationDeathTest.ArgParse_inputfile_short

[WARNING] /home/ptheywood/code/flamegpu/FLAMEGPU2/build/_deps/googletest-src/googletest/src/gtest-death-test.cc:1121:: Death tests use fork(), which is unsafe particularly in a threaded context. For this test, Google Test detected 4 threads. See https://github.com/google/googletest/blob/master/docs/advanced.md#death-tests-and-threads for more explanation and suggested solutions, especially if this is the last message you see before your test times out.
[       OK ] TestSimulationDeathTest.ArgParse_inputfile_short (8 ms)
[----------] 1 test from TestSimulationDeathTest (8 ms total)

...

[==========] 871 tests from 77 test suites ran. (339195 ms total)
[  PASSED  ] 871 tests.

  YOU HAVE 145 DISABLED TESTS
```

Pytest showing the skip

```
python3 -m pytest ../tests/swig/python/gpu/test_cuda_simulation.py
========================================================== test session starts ===========================================================
platform linux -- Python 3.9.5, pytest-7.0.1, pluggy-1.0.0
rootdir: /home/ptheywood/code/flamegpu/FLAMEGPU2
collected 19 items                                                                                                                       

../tests/swig/python/gpu/test_cuda_simulation.py .....s.............                                                               [100%]

===================================================== 18 passed, 1 skipped in 6.14s ======================================================
```

2022-02-24 10:54 UTC, Robadob commented
Python tests ran to completion (but had some failures, despite `USE_GLM` off):

```
=============================================== short test summary info ===============================================
FAILED gpu/test_cuda_ensemble.py::TestCUDAEnsemble::test_setStepLog - AttributeError: 'SwigPyObject' object has no at...
FAILED io/test_logging.py::LoggingTest::test_CUDAEnsembleSimulate - AttributeError: 'SwigPyObject' object has no attr...
FAILED io/test_logging.py::LoggingTest::test_CUDASimulationSimulate - AttributeError: 'SwigPyObject' object has no at...
FAILED io/test_logging.py::LoggingTest::test_CUDASimulationStep - AttributeError: 'SwigPyObject' object has no attrib...
FAILED io/test_logging_exceptions.py::LoggingExceptionTest::test_AgentLogFrameExceptions - AttributeError: 'SwigPyObj...
FAILED io/test_logging_exceptions.py::LoggingExceptionTest::test_LogFrameExceptions - AttributeError: 'SwigPyObject' ...
FAILED io/test_logging_exceptions.py::LoggingExceptionTest::test_LoggerSupportedFileType - TypeError: exportLog() mis...
FAILED runtime/test_host_environment.py::HostEnvironmentTest::test_exception_property_read_only - pyflamegpu.pyflameg...
FAILED runtime/messaging/test_brute_force.py::TestMessage_BruteForce::test_Optional2 - AssertionError: assert -192 ==...
================================ 9 failed, 544 passed, 5 skipped in 1582.41s (0:26:22) ================================
```

C tests had 1 failure, which I believe is the test you modified. Will investigate:
```
[----------] Global test environment tear-down
[==========] 991 tests from 79 test suites ran. (597022 ms total)
[  PASSED  ] 990 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] TestSimulationDeathTest.ArgParse_inputfile_short

 1 FAILED TEST
  YOU HAVE 25 DISABLED TESTS
```

2022-02-24 10:55 UTC, Robadob commented
This is the actual failure details.

```
[ RUN      ] TestSimulationDeathTest.ArgParse_inputfile_short
C:\Users\Robadob\fgpu2\build\_deps\googletest-src\googletest\src/gtest-port.cc(865): error: Failed
Syntax error at index 0 in simple regular expression "[.]*": '[' is unsupported.
C:\Users\Robadob\fgpu2\build\_deps\googletest-src\googletest\src/gtest-port.cc(865): error: Failed
Syntax error at index 2 in simple regular expression "[.]*": ']' is unsupported.
Running main() from c:\users\robadob\fgpu2\tests\helpers\main.cu
c:\users\robadob\fgpu2\tests\test_cases\gpu\test_cuda_simulation.cu(107): error: Death test: c.initialise(sizeof(argv) / sizeof(char*), argv)
    Result: died but not with expected error.
  Expected: contains regular expression "[.]*"
Actual msg:
[  DEATH   ] Loading input file 'I_DO_NOT_EXIST.xml' failed!
[  DEATH   ] Detail: C:\Users\Robadob\fgpu2\src\flamegpu\io\XMLStateReader.cpp(90): TinyXML error: File could not be opened.
[  DEATH   ]  Error code: 3
[  FAILED  ] TestSimulationDeathTest.ArgParse_inputfile_short (2988 ms)
```

2022-02-24 11:04 UTC, Robadob requested changes
Current C test doesn't work on Windows.

2022-02-24 11:04 UTC, Robadob commented on tests/test_cases/gpu/test_cuda_simulation.cu
> +    EXPECT_EXIT(c.initialise(sizeof(argv) / sizeof(char*), argv), testing::ExitedWithCode(EXIT_FAILURE), "[.]*");  // File doesn't exist
On windows it says regex `[` and `]` are unsupported.

Using `".*"` as matcher works, however a more specific `".*Loading input file '.*' failed!.*"` also works which would be preferred.

2022-02-24 12:09 UTC, Robadob approved these changes

2022-02-24 12:34 UTC, merged